CMake build for Windows (#6)
Summary:
Slight code change since DLLs can't have exported thread_local members (see [error C2492](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2492?view=msvc-160)).

Pull Request resolved: https://github.com/facebookincubator/dispenso/pull/6

Reviewed By: AndreiFB

Differential Revision: D27221646

Pulled By: graphicsMan

fbshipit-source-id: 58e17fa9fb6a50c49802e683eae7439f9e754728