remove template specification (#36)
Summary:
# PR Details

fix compilation error with gcc 14 (Fedora 40)

## Description

Remove template specification to avoid error `error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]`

## Related Issue

https://github.com/facebookincubator/dispenso/issues/35

## Motivation and Context

Pull Request resolved: https://github.com/facebookincubator/dispenso/pull/36

Test Plan:
I've compiled the code with  the g++ from ubuntu 20.04, 22.04 and 24.04 docker images  and g++  from Fedora 40 and executed the tests with success except for the test Priorty.PriorityGetsCycles

## Types of changes

- [ ] Docs change
- [ ] Refactoring
- [ ] Dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] I have run clang-format.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed, including in ASAN and TSAN modes (if available on your platform).

Reviewed By: RomanFedotovFB

Differential Revision: D62474193

Pulled By: graphicsMan

fbshipit-source-id: 34a27756774d25f85a8d6cdd54397c3a33627072