Fix unused result warnings
Summary:
`priority.cpp` has calls to `nice` with the result ignored, which fails on Fedora

Per https://stackoverflow.com/questions/7271939/warning-ignoring-return-value-of-scanf-declared-with-attribute-warn-unused-r#comment95629501_7273026
and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425#c34

casting to `(void)` is insufficient, but doing a logical negation prior to casting works
```
/builddir/build/BUILD/dispenso-1.2.0/dispenso/priority.cpp: In function ‘bool dispenso::setCurrentThreadPriority(ThreadPriority)’:
/builddir/build/BUILD/dispenso-1.2.0/dispenso/priority.cpp:136:11: error: ignoring return value of ‘int nice(int)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  136 |       nice(10);
      |       ~~~~^~~~
/builddir/build/BUILD/dispenso-1.2.0/dispenso/priority.cpp:140:11: error: ignoring return value of ‘int nice(int)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  140 |       nice(0);
      |       ~~~~^~~
/builddir/build/BUILD/dispenso-1.2.0/dispenso/priority.cpp:152:11: error: ignoring return value of ‘int nice(int)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  152 |       nice(static_cast<int>(20 - rlim.rlim_max));
      |       ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Reviewed By: graphicsMan

Differential Revision: D52514024

fbshipit-source-id: 4a0a1b74dc83bf2542b9052343bbdfba2d755a84