Fix redundant move in initialization warning
Summary:
`timed_task.cpp` has a redundant move, which fails when building the Fedora package on newer GCCs with the default settings.

```
/builddir/build/BUILD/dispenso-1.2.0/dispenso/timed_task.cpp: In member function ‘void dispenso::TimedTaskScheduler::timeQueueRunLoop()’:
/builddir/build/BUILD/dispenso-1.2.0/dispenso/timed_task.cpp:86:28: error: redundant move in initialization [-Werror=redundant-move]
   86 |       auto next = std::move(tasks_.top());
      |                   ~~~~~~~~~^~~~~~~~~~~~~~
/builddir/build/BUILD/dispenso-1.2.0/dispenso/timed_task.cpp:86:28: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
```

Reviewed By: graphicsMan

Differential Revision: D52513860

fbshipit-source-id: bf3e9c9a448b00a22498648a5592ca188c49d915