Update googletest to version 1.12.1 for modern clang versions (#18)
Summary:
Tests were failing to build due to:

```
error: definition of implicit copy constructor for 'PolymorphicAction<testing::internal::ReturnNullAction>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(PolymorphicAction);
```
# PR Details

Modified tests/CMakeLists.txt to use GoogleTest release-1.12.1

## Description

## Related Issue

## Motivation and Context

Pull Request resolved: https://github.com/facebookincubator/dispenso/pull/18

Test Plan:
## Types of changes

- [ ] Docs change
- [ ] Refactoring
- [x] Dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] I have run clang-format.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed, including in ASAN and TSAN modes (if available on your platform).

Reviewed By: elliotsegal-fb

Differential Revision: D38684496

Pulled By: graphicsMan

fbshipit-source-id: 9e7f128496b2d0712af66c2d940130d1860da8a7