Include cstdlib for malloc and free (#26)
Summary:
# PR Details

Include `<cstdlib>` in platform.h since it uses `malloc` and `free`

## Description

Include `<cstdlib>` in platform.h since it uses `malloc` and `free`

## Related Issue

https://trac.macports.org/ticket/69098

## Motivation and Context

It fixes these build errors on OS X 10.10 and 10.11 systems:

```
In file included from /path/to/dispenso/detail/per_thread_info.cpp:8:
In file included from /path/to/dispenso/../dispenso/detail/per_thread_info.h:10:
/path/to/dispenso/../dispenso/platform.h:130:41: error: no member named 'malloc' in the global namespace
  char* ptr = reinterpret_cast<char*>(::malloc(bytes + alignment));
                                      ~~^
/path/to/dispenso/../dispenso/platform.h:152:5: error: no member named 'free' in the global namespace
  ::free(reinterpret_cast<void*>(recovered));
  ~~^
2 errors generated.
```

Other errors remain on these platforms but this fix gets it one step closer to building.

Pull Request resolved: https://github.com/facebookincubator/dispenso/pull/26

Test Plan:
I built dispenso 1.2.0 on OS X 10.11 and noticed the error. I applied my change and rebuilt the code and the error was no longer present.

## Types of changes

- [ ] Docs change
- [ ] Refactoring
- [ ] Dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have run clang-format.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed, including in ASAN and TSAN modes (if available on your platform).

Reviewed By: RomanFedotovFB

Differential Revision: D53277863

Pulled By: graphicsMan

fbshipit-source-id: 76b72552f074b9c0682a009e95018be513d8297f